# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: price.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bprice.proto\x12\x05price\">\n\x0cPriceRequest\x12\x11\n\tmodelCode\x18\x01 \x01(\t\x12\r\n\x05\x63olor\x18\x02 \x01(\t\x12\x0c\n\x04year\x18\x03 \x01(\x05\"1\n\nPriceReply\x12\r\n\x05price\x18\x01 \x01(\x05\x12\x14\n\x0c\x63urrencyCode\x18\x02 \x01(\t2<\n\x06Pricer\x12\x32\n\x08GetPrice\x12\x13.price.PriceRequest\x1a\x11.price.PriceReplyb\x06proto3')



_PRICEREQUEST = DESCRIPTOR.message_types_by_name['PriceRequest']
_PRICEREPLY = DESCRIPTOR.message_types_by_name['PriceReply']
PriceRequest = _reflection.GeneratedProtocolMessageType('PriceRequest', (_message.Message,), {
  'DESCRIPTOR' : _PRICEREQUEST,
  '__module__' : 'price_pb2'
  # @@protoc_insertion_point(class_scope:price.PriceRequest)
  })
_sym_db.RegisterMessage(PriceRequest)

PriceReply = _reflection.GeneratedProtocolMessageType('PriceReply', (_message.Message,), {
  'DESCRIPTOR' : _PRICEREPLY,
  '__module__' : 'price_pb2'
  # @@protoc_insertion_point(class_scope:price.PriceReply)
  })
_sym_db.RegisterMessage(PriceReply)

_PRICER = DESCRIPTOR.services_by_name['Pricer']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PRICEREQUEST._serialized_start=22
  _PRICEREQUEST._serialized_end=84
  _PRICEREPLY._serialized_start=86
  _PRICEREPLY._serialized_end=135
  _PRICER._serialized_start=137
  _PRICER._serialized_end=197
# @@protoc_insertion_point(module_scope)
